import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { escapeXml } from './validate.ts';

// The STUB generator. It produces a minimal-but-valid presentation: a single self-contained SVG
// of the title + write-up, an index.html wrapper, and a manifest.json. The artifact filenames and
// the manifest schema are the OUTPUT CONTRACT that #3's real Prezi generator must fulfill
// unchanged (spec §5, open item #3). No research, no real zoom narrative — that's #2/#3.

export const SCHEMA_VERSION = 1;
export const GENERATOR = 'stub@1';

export interface GenInput {
  id: number;
  title: string;
  sourceWriteup: string;
  slug: string;
}

export interface Manifest {
  schemaVersion: number;
  generator: string;
  generatedAt: string; // ISO 8601
  presentationId: number;
  title: string;
  slug: string;
  entry: string;
  artifacts: string[];
}

export type Generator = (input: GenInput, outDir: string) => Promise<Manifest>;

// Wrap text into lines of at most `width` chars, splitting on whitespace.
function wrap(text: string, width: number): string[] {
  const out: string[] = [];
  for (const para of text.split(/\n/)) {
    if (para.trim() === '') {
      out.push('');
      continue;
    }
    let line = '';
    for (const word of para.split(/\s+/)) {
      if (line === '') {
        line = word;
      } else if ((line + ' ' + word).length <= width) {
        line += ' ' + word;
      } else {
        out.push(line);
        line = word;
      }
    }
    if (line) out.push(line);
  }
  return out;
}

export function renderSvg(title: string, writeup: string): string {
  const width = 1280;
  const height = 720;
  const bodyLines = wrap(writeup, 72).slice(0, 24); // cap so the stub stays one readable slide
  const startY = 220;
  const lineH = 30;
  const tspans = bodyLines
    .map((line, i) => `<tspan x="80" y="${startY + i * lineH}">${escapeXml(line)}</tspan>`)
    .join('\n      ');

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" width="${width}" height="${height}" role="img" aria-label="${escapeXml(title)}">
  <rect width="${width}" height="${height}" fill="#0b1020"/>
  <text x="80" y="130" font-family="Georgia, 'Times New Roman', serif" font-size="56" fill="#e8ecff" font-weight="700">${escapeXml(title)}</text>
  <line x1="80" y1="160" x2="${width - 80}" y2="160" stroke="#3a4a8c" stroke-width="2"/>
  <text font-family="-apple-system, system-ui, sans-serif" font-size="20" fill="#c2cbe8">
      ${tspans}
  </text>
  <text x="80" y="${height - 40}" font-family="system-ui, sans-serif" font-size="14" fill="#5a6aa0">Generated by agentic-prezi (stub generator)</text>
</svg>
`;
}

function renderIndexHtml(title: string, svg: string): string {
  // Self-contained: the SVG is inlined (same-origin markup, not script) so the published origin's
  // strict CSP (default-src 'self') serves it without any external fetches.
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeXml(title)}</title>
<link rel="stylesheet" href="styles.css">
</head>
<body>
<main class="stage">
${svg}
</main>
</body>
</html>
`;
}

const STYLES = `:root { color-scheme: dark; }
* { box-sizing: border-box; }
html, body { margin: 0; height: 100%; background: #05060d; }
.stage { display: grid; place-items: center; min-height: 100vh; padding: 2vmin; }
.stage svg { width: min(100%, 1280px); height: auto; border-radius: 8px; box-shadow: 0 8px 40px rgba(0,0,0,.5); }
`;

export const generateStub: Generator = async (input, outDir) => {
  await mkdir(outDir, { recursive: true });
  const svg = renderSvg(input.title, input.sourceWriteup);
  const indexHtml = renderIndexHtml(input.title, svg);

  const manifest: Manifest = {
    schemaVersion: SCHEMA_VERSION,
    generator: GENERATOR,
    generatedAt: new Date().toISOString(),
    presentationId: input.id,
    title: input.title,
    slug: input.slug,
    entry: 'index.html',
    artifacts: ['index.html', 'presentation.svg', 'styles.css', 'manifest.json'],
  };

  await Promise.all([
    writeFile(join(outDir, 'presentation.svg'), svg, 'utf8'),
    writeFile(join(outDir, 'index.html'), indexHtml, 'utf8'),
    writeFile(join(outDir, 'styles.css'), STYLES, 'utf8'),
    writeFile(join(outDir, 'manifest.json'), JSON.stringify(manifest, null, 2), 'utf8'),
  ]);

  return manifest;
};
